package com.sickle.pojo.website;

import java.util.Date;

import com.gwtent.reflection.client.annotations.Reflect_Domain;
import com.sickle.uireflect.FieldType;
import com.sickle.uireflect.Reflect_Field;

/**
 * Message generated by hbm2java
 */
@Reflect_Domain
public class Message implements java.io.Serializable
{

	private static final long serialVersionUID = 7346379941099118836L;
	@Reflect_Field(type = FieldType.Long,isId = true)
	private Long id;
	@Reflect_Field(title="发信人")
	private int from;
	@Reflect_Field(title="收信人")
	private int to;
	@Reflect_Field(title="是否已读")
	private String hasread;
	@Reflect_Field(title="接收时间")
	private Date date;
	@Reflect_Field(title="内容")
	private String content;
	@Reflect_Field(title="标题")
	private String title;
	@Reflect_Field(title="类型")
	private String type;

	public Message( )
	{
	}

	public Message( int from, int to )
	{
		this.from = from;
		this.to = to;
	}

	public Message( int from, int to, String hasread, Date date,
			String content, String title, String type )
	{
		this.from = from;
		this.to = to;
		this.hasread = hasread;
		this.date = date;
		this.content = content;
		this.title = title;
		this.type = type;
	}

	public Long getId( )
	{
		return this.id;
	}

	public void setId( Long id )
	{
		this.id = id;
	}

	public int getFrom( )
	{
		return this.from;
	}

	public void setFrom( int from )
	{
		this.from = from;
	}

	public int getTo( )
	{
		return this.to;
	}

	public void setTo( int to )
	{
		this.to = to;
	}

	public String getHasread( )
	{
		return this.hasread;
	}

	public void setHasread( String hasread )
	{
		this.hasread = hasread;
	}

	public Date getDate( )
	{
		return this.date;
	}

	public void setDate( Date date )
	{
		this.date = date;
	}

	public String getContent( )
	{
		return this.content;
	}

	public void setContent( String content )
	{
		this.content = content;
	}

	public String getTitle( )
	{
		return this.title;
	}

	public void setTitle( String title )
	{
		this.title = title;
	}

	public String getType( )
	{
		return this.type;
	}

	public void setType( String type )
	{
		this.type = type;
	}

}
